name: SwiftPrintBLE
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    PRODUCT_NAME: SwiftPrint BLE
configs:
  Debug: debug
  Release: release
targets:
  SwiftPrintBLE:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: Config
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.whitetang.swiftprintble
        INFOPLIST_FILE: Config/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
